lib/has_my_gsuite_been_pwned_web/router.ex
defmodule HasMyGsuiteBeenPwnedWeb.Router do
  use HasMyGsuiteBeenPwnedWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HasMyGsuiteBeenPwnedWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/auth", AuthController, :index
    get "/oauth-callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", HasMyGsuiteBeenPwnedWeb do
  #   pipe_through :api
  # end

  # Fetch the current user from the session and add it to `conn.assigns`. This
  # will allow you to have access to the current user in your views with
  # `@current_user`.
  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end
end

lib/has_my_gsuite_been_pwned_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <%= if @current_user do %>
      <h2>Welcome, <%= user_name(@conn) %>!</h2>
      <p><img src="<%= @current_user.avatar %>" class="img-circle"/></p>
      <p><%= link "Logout", to: auth_path(@conn, :delete), method: :delete, class: "btn btn-danger" %></p>
    <% else %>
      <br>
      <br>

      <a class="btn btn-primary btn-lg" href="<%= auth_path @conn, :index %>">
        <i class="fa fa-google"></i>
        Sign in with Google
      </a>
    <% end %>
  </div>
</div>